### ISSUE TITLE
`min-height` doesn't work as it should with `overflow-scroll`.

### ISSUE THREAD

**Issue by Geeknerd1337** [sboxgame/issues#2584]
### Describe the bug

When using the `min-height` property with a containing panel using `overflow: scroll`, I would expect any child flex panels to be able to expand fully, however, even with `overflow: scroll` enabled, the elements can't expand past their minimum height.

### To Reproduce

Say you have the following html:
```html
<root class="page">
    <div class="content">
        <div class="jobsContainer" @ref="JobsContainer"></div>
    </div>
</root>
```

With the following scss:
```scss
.page {
    background-color: #F3F2EF;
    width: 100%;
    height: 100%;
    overflow: scroll;

    .content {
        width: 100%;
        min-height: 100%;
        flex-direction: column;
        align-items: center;

        .jobsContainer {
            flex-direction: column;
            width: 50%;
            background-color: white;
            border: 1px solid green;
        }
    }
}
```

Then a nested item:
```html
<root class="job-button">

</root>
```
With the following scss:
```scss
.job-button {
    flex-direction: row;
    color: black;
    border: 1px solid red;
    align-items: center;
    padding: 20px;
    height: 2000px;
}
```

You'll notice that instead of having a couple 2000px tall entries, expanding the list and allowing you to scroll through it:
![image](https://user-images.githubusercontent.com/15205856/203678105-1254dbef-1190-4f82-a99a-4a4b2fa59d97.png)

Instead you see that it mearly maxes out at the maximum height of `100%` defined in `.page`, not expanding the `.content` as needed.

### Expected behavior

https://jsfiddle.net/1evtxuqn/21/

This JS Fiddle shows the intended behavior. As the `.jobItem` items expand in height, they overflow the containing element using the `min-height` property.

![image](https://user-images.githubusercontent.com/15205856/203678646-2e892b6e-40c0-442d-9fe1-b5af0725c192.png)

### Additional context

You can work around this right now by doing something like `min-height: 200%` but this leaves a lot of unnecessary white space.
