### ISSUE TITLE
`transform: rotate` breaks panel culling

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2823]
### Describe the bug

After the recent culling fixes it is now possible to extend panel size beyond the screen size and then transform it back in screen whenever needed. However when adding a `transform: rotate(Xdeg);` of any X degrees this behavior changes.

I have included 2 videos, one in which the top and bottom panels seem to cull out because of the rotation and the other panels have an issue with sizing. And the other one without any rotation.

CSS of the top and bottom panels:
```CSS
    .topBar {
        position: absolute;
        background-color: black;
        top: -100%;
        width: 100%;
        height: 100%;
    }

    .bottomBar {
        position: absolute;
        background-color: black;
        bottom: -100%;
        width: 100%;
        height: 100%;
    }
```

## No rotation

https://user-images.githubusercontent.com/4988198/214275914-93688793-dec6-410f-91dc-cd4cfd77f182.mp4

## transform: rotate(20deg)

https://user-images.githubusercontent.com/4988198/214275937-defed7d6-ce29-4c18-8982-3a760cb5da5b.mp4

### To Reproduce

/

### Expected behavior

/

**Comment by handsomematt** [comment]
Could you supply all the code up to the transforms themselves? And does this happen with ui_cull 0

I think you might be going beyond what the UI system is for really and you'd probably be better off drawing this manually.

**Comment by timmybo5** [comment]
I didn't even know manual drawing was an option, I'll have to look into that.
It seems `ui_cull` does not affect the behavior, here's all the code, do mind it's very WIP :)

```CSHARP
public class SniperScope : Panel
{
    Panel LensWrapper;

    public SniperScope(string lensTexture, string scopeTexture)
    {
        StyleSheet.Load("/swb_base/ui/SniperScope.scss");

        if (scopeTexture != null)
            Add.Panel("leftBar");

        LensWrapper = Add.Panel("lensWrapper");
        LensWrapper.Add.Image(lensTexture, "lens");

        if (scopeTexture != null)
        {
            LensWrapper.Add.Image(scopeTexture, "scope");

            Add.Panel("rightBar");
            Add.Panel("topBar");
            Add.Panel("bottomBar");
        }
    }

    public override void Tick()
    {
        base.Tick();

        if (Game.LocalPawn is not PlayerBase player) return;
        if (player.ActiveChild is not WeaponBase weapon) return;

        // Scope size
        var scopeSize = Screen.Height * ScaleFromScreen;
        LensWrapper.Style.Width = Length.Pixels(scopeSize);

        // Show when zooming
        Style.Opacity = !weapon.IsScoped ? 1 : 1;

        //// Movement impact
        var velocity = player.Velocity;
        var velocityMove = (velocity.y + velocity.x) / 2;
        var lensBob = 0f;

        if (velocityMove != 0)
        {
            lensBob += MathF.Sin(RealTime.Now * 20f) * 2f;
        }

        Style.MarginTop = Length.Percent((velocity.z * 0.05f) + lensBob);
    }
}
```

```CSS
SniperScope {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(20deg);
    overflow: visible;

    .lensWrapper {
        width: 100%;
    }

    .lens {
        height: 100%;
        width: 100%;
    }

    .scope {
        position: absolute;
        height: 100%;
        width: 100%;
    }

    .leftBar,
    .rightBar {
        background-color: black;
        height: 100%;
        flex-grow: 1;
    }

    .topBar {
        position: absolute;
        background-color: black;
        top: -100%;
        width: 100%;
        height: 100%;
    }

    .bottomBar {
        position: absolute;
        background-color: black;
        bottom: -100%;
        width: 100%;
        height: 100%;
    }
}

```
