### ISSUE TITLE
 gap is badly implemented

### ISSUE THREAD

**Issue by dictateurfou** [sboxgame/issues#3009]
### What it is?

gap must be an equivalent of calc for width when you have margin

exemple:
```css
.parent{
    gap:10px;
}
.child{
   width:20%; /*show 5 element and have 10px of margin (gap)*/
}
```
equivalent of gap
```css
.child{
   margin: 10px;
   width: calc(20% - 20px); // show 5 element and calcul margin for correct size
}
```

current behavior gap is a equivalent for margin so we have nothing to fill a container with a defined number of elements per row

### **the expected result should be**

![](https://i.gyazo.com/f281326cb45fe3592947d41307a7fe5d.png)

### **currently the result is**

![](https://i.gyazo.com/fa8b3d9e3bcc87acc8652bfc2de0a950.png)

we can get the right result by doing the calculation by hand but if the resolution goes from 1080p to 720p we get 4 elements instead of 5 I did not find any solution to obtain a good result
