### ISSUE TITLE
Add `border-image-tint` to CSS style properties

### ISSUE THREAD

**Issue by Fortune117** [sboxgame/issues#3057]
### For?

S&Box

### What can't you do?

I'm unable to tint the color of the border image from the border-image property.
Something like this:
```CSS
StatusEffectPanel
{
  height: 100%;
  aspect-ratio: 1;

  background-color: rgba(0, 0, 0, 0.5);

  border-image: url("textures/ui/ui_panel_border.png") 31 31 round;
  border-image-tint: red; //<------ this one

  border: 8px;
}
```

### How would you like it to work?

Same way as `background-image-tint`

### What have you tried?

Tried setting background color, tint colors, regular colors, border color, no luck.
