### ISSUE TITLE
SCSS Zero width/height elements with borders break

### ISSUE THREAD

**Issue by ogniK5377** [sboxgame/issues#90]
**Describe the bug**
An element with zero width and height cannot have borders. Typically this is how you make pure CSS triangles, however, this doesn't seem to work at all. It ends up with creating graphical artifacts as well

**To Reproduce**
```scss
    // Default broken border
    .broken {
        width: 0;
        height: 0;
        border: 200px solid #1007A4;
    }
    // Triangle test
    .triangle {
        position: absolute;
        width: 0;
        height: 0;
        border-left: 200px solid transparent;
        border-right: 200px solid transparent;
        border-bottom: 400px solid #1007A4;
    }
```

**Expected behavior**
The border should be shown:
.broken
![image](https://user-images.githubusercontent.com/25727384/116881004-11c99f80-ac66-11eb-91be-44d5daaa212f.png)

.triangle
![image](https://user-images.githubusercontent.com/25727384/116881482-a6cc9880-ac66-11eb-89f4-03e893c84df8.png)

**Screenshots**
Reproduction code result:
.broken
![image](https://user-images.githubusercontent.com/25727384/116880670-a5e73700-ac65-11eb-946a-dc3a628acdac.png)

.triangle
![image](https://user-images.githubusercontent.com/25727384/116881677-e72c1680-ac66-11eb-85d9-c92c301829c9.png)

**Additional context**
The result current in-game seems to flicker as well
